### ISSUE TITLE
porting more complex functions

### ISSUE THREAD

**Issue by pachadotdev** [thisisnic/cpp_in_r#1]
hi
I have github.com/pachadotdev/leontief and I hear very good things from cpp11, but there's no cpp11armadillo or so
do you think that would appear sometime?

**Comment by thisisnic** [comment]
Hey Pacha! :) So this repo is not really an open-source project as such; it's just where I'm putting things while I'm learning, that I may turn into resources for others at some point (and may well not - not enough hours in the day, right?)

WRT your question, I have no idea.
